# Generated by Django 4.0.2 on 2022-02-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='program_finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
