# Generated by Django 4.0.2 on 2022-02-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_program_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='program_finished',
            field=models.BooleanField(default=False),
        ),
    ]
