# Generated by Django 4.0.2 on 2022-02-16 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_program_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ai_program',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ai_program'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.property'),
        ),
    ]
