# Generated by Django 4.0.2 on 2022-02-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_ai_program_alter_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
