# Generated by Django 4.0.2 on 2022-02-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_profile_customerprofile_alter_property_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='pic',
            new_name='property',
        ),
    ]
