# Generated by Django 4.0.2 on 2022-02-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_pic_customerprofile_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='ai_program',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='ai_program',
            field=models.ManyToManyField(blank=True, null=True, to='app.AI_Program'),
        ),
    ]
