# Generated by Django 4.0.2 on 2022-02-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customerprofile_ai_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='ai_program',
            field=models.ManyToManyField(blank=True, to='app.AI_Program'),
        ),
    ]
