# Generated by Django 4.0.2 on 2022-02-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_customerprofile_program_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='ai_program',
            field=models.ManyToManyField(blank=True, related_name='enrolled_programs', to='app.AI_Program'),
        ),
    ]
