# Generated by Django 4.0.2 on 2022-02-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_customerprofile_ai_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nlsid', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='NLSID')),
                ('vid', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='VID')),
                ('weight', models.IntegerField(blank=True, default=0, max_length=20, null=True, verbose_name='Weight')),
                ('codition_score', models.IntegerField(blank=True, default=0, max_length=20, null=True, verbose_name='Condition Score')),
                ('imf', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='IMF')),
                ('note', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Note')),
                ('breed', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Breed')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='cows',
            field=models.ManyToManyField(blank=True, to='app.CowTable'),
        ),
    ]
