# Generated by Django 4.0.2 on 2022-02-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cowtable_property_cows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowtable',
            name='codition_score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Condition Score'),
        ),
        migrations.AlterField(
            model_name='cowtable',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Weight'),
        ),
    ]
