# Generated by Django 4.0.2 on 2022-02-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_cowtable_codition_score_alter_cowtable_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowtable',
            name='interactions',
            field=models.CharField(blank=True, choices=[('TAS', 'TAS'), ('NSW', 'NSW'), ('VIC', 'VIC'), ('QLD', 'QLD'), ('NT', 'NT'), ('SA', 'SA'), ('WA', 'WA')], default='', max_length=2000, null=True, verbose_name='Interaction'),
        ),
    ]
