# Generated by Django 4.0.2 on 2022-02-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_cowtable_interactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cowtable',
            old_name='codition_score',
            new_name='condition_score',
        ),
    ]
