# Generated by Django 4.0.2 on 2022-02-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_codition_score_cowtable_condition_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowtable',
            name='ema',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='EMA'),
        ),
    ]
