# Generated by Django 4.0.2 on 2022-02-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_cowtable_ema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowtable',
            name='note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Note'),
        ),
    ]
