# Generated by Django 4.0.2 on 2022-02-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_ai_program_gnrh_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai_program',
            old_name='injection_pgndn_date',
            new_name='prosto_injection_date',
        ),
        migrations.RenameField(
            model_name='ai_program',
            old_name='injection_pgndn_status',
            new_name='prosto_injection_status',
        ),
        migrations.RenameField(
            model_name='ai_program',
            old_name='pull_seed_out_date',
            new_name='remove_seed_date_date',
        ),
        migrations.RenameField(
            model_name='ai_program',
            old_name='pull_seed_out_status',
            new_name='remove_seed_status',
        ),
    ]
