# Generated by Django 4.0.2 on 2022-02-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_injection_pgndn_date_ai_program_prosto_injection_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai_program',
            old_name='remove_seed_date_date',
            new_name='remove_seed_date',
        ),
    ]
