# Generated by Django 4.0.2 on 2022-02-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_remove_seed_date_date_ai_program_remove_seed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_program',
            name='gnrh_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ai_program',
            name='insemination_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ai_program',
            name='pregnancy_test_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ai_program',
            name='prosto_injection_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ai_program',
            name='remove_seed_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ai_program',
            name='seeder_injection_status',
            field=models.BooleanField(default=False),
        ),
    ]
