# Generated by Django 4.0.2 on 2022-02-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_ai_program_gnrh_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cowtable',
            old_name='interactions',
            new_name='interaction',
        ),
    ]
