# Generated by Django 4.0.2 on 2022-02-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_interactions_cowtable_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowtable',
            name='condition_score',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Condition Score'),
        ),
        migrations.AlterField(
            model_name='cowtable',
            name='interaction',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Interaction'),
        ),
        migrations.AlterField(
            model_name='cowtable',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Weight'),
        ),
    ]
