# Generated by Django 4.0.2 on 2022-02-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_cowtable_condition_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='billing_suburb',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='property_suburb',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
