# Generated by Django 4.0.2 on 2022-02-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_customerprofile_billing_suburb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='billing_postcode',
            field=models.IntegerField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='property_postcode',
            field=models.IntegerField(blank=True, default='', max_length=4, null=True),
        ),
    ]
