# Generated by Django 4.0.2 on 2022-02-19 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_customerprofile_billing_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='billing_postcode',
            field=models.CharField(blank=True, default='', max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='property_postcode',
            field=models.CharField(blank=True, default='', max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
