# Generated by Django 4.0.2 on 2022-02-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_customerprofile_billing_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='abn',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='billing_address',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='billing_state',
            field=models.CharField(blank=True, choices=[('TAS', 'TAS'), ('NSW', 'NSW'), ('VIC', 'VIC'), ('QLD', 'QLD'), ('NT', 'NT'), ('SA', 'SA'), ('WA', 'WA')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='billing_suburb',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='property_address',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='property_state',
            field=models.CharField(blank=True, choices=[('TAS', 'TAS'), ('NSW', 'NSW'), ('VIC', 'VIC'), ('QLD', 'QLD'), ('NT', 'NT'), ('SA', 'SA'), ('WA', 'WA')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='property_suburb',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
