# Generated by Django 4.0.2 on 2022-02-19 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_customerprofile_abn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowtable',
            name='breed',
            field=models.CharField(blank=True, choices=[('Jersey', 'Jersey'), ('Holstein Fresian', 'Holstein Fresian'), ('Illawarra', 'Illawarra'), ('Angus', 'Angus'), ('Charolet', 'Charolet')], default='', max_length=2000, null=True, verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='cowtable',
            name='condition_score',
            field=models.CharField(blank=True, default='', max_length=1, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')], verbose_name='Condition Score'),
        ),
        migrations.AlterField(
            model_name='cowtable',
            name='nlsid',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='NLSID'),
        ),
    ]
