# Generated by Django 4.0.2 on 2022-02-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_property_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai_program',
            old_name='remove_seed_date',
            new_name='cidrs_out_date',
        ),
        migrations.RenameField(
            model_name='ai_program',
            old_name='remove_seed_status',
            new_name='cidrs_out_status',
        ),
    ]
