# Generated by Django 4.0.2 on 2022-02-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_remove_seed_date_ai_program_cidrs_out_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai_program',
            old_name='prosto_injection_date',
            new_name='bomerol_injection_date',
        ),
        migrations.RenameField(
            model_name='ai_program',
            old_name='prosto_injection_status',
            new_name='bomerol_injection_status',
        ),
    ]
