# Generated by Django 4.0.2 on 2022-02-20 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_prosto_injection_date_ai_program_bomerol_injection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d[0-9]..\\s\\d[0-9].\\s\\d[0-9].')]),
        ),
    ]
