# Generated by Django 4.0.2 on 2022-02-20 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_customerprofile_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowtable',
            name='nlsid',
            field=models.CharField(default='', max_length=16, validators=[django.core.validators.RegexValidator('^\\w+[A-Za-z0-9]{15}')], verbose_name='NLSID'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='abn',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='billing_postcode',
            field=models.CharField(blank=True, default='', max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d[0-9]\\s\\d[0-9].\\s\\d[0-9].\\s\\d[0-9].')]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='property_postcode',
            field=models.CharField(default='', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')]),
        ),
    ]
