# Generated by Django 4.0.2 on 2022-02-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_customerprofile_abn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_program',
            name='last_completed_action',
            field=models.CharField(blank=True, default='N/A', max_length=8, null=True, verbose_name='Last completed action'),
        ),
    ]
