# Generated by Django 4.0.2 on 2022-02-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_ai_program_last_completed_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai_program',
            old_name='bomerol_injection_date',
            new_name='pg_injection_date',
        ),
        migrations.RenameField(
            model_name='ai_program',
            old_name='bomerol_injection_status',
            new_name='pg_injection_status',
        ),
    ]
