# Generated by Django 4.0.2 on 2022-02-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_ai_program_bomerol_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_program',
            name='last_completed_action',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True, verbose_name='Last completed action'),
        ),
    ]
